-- AlterTable
ALTER TABLE "CONTADOR" ADD COLUMN     "empresaId" INTEGER;

-- AlterTable
ALTER TABLE "USER" ADD COLUMN     "flg_master" BOOLEAN DEFAULT false;

-- AddForeignKey
ALTER TABLE "CONTADOR" ADD CONSTRAINT "CONTADOR_empresaId_fkey" FOREIGN KEY ("empresaId") REFERENCES "EMPRESA"("id") ON DELETE SET NULL ON UPDATE CASCADE;
