-- AlterTable
ALTER TABLE "DOCUMENTO" ALTER COLUMN "CNPJCli" DROP NOT NULL,
ALTER COLUMN "nomeCli" DROP NOT NULL,
ALTER COLUMN "tipoDoc" DROP NOT NULL;

-- CreateTable
CREATE TABLE "CONTADOR_EMPRESA" (
    "contadorId" INTEGER NOT NULL,
    "cnpj" VARCHAR(18) NOT NULL,
    "hashCNPJ" VARCHAR(64) NOT NULL,

    CONSTRAINT "CONTADOR_EMPRESA_pkey" PRIMARY KEY ("contadorId","cnpj")
);

-- AddForeignKey
ALTER TABLE "CONTADOR_EMPRESA" ADD CONSTRAINT "CONTADOR_EMPRESA_contadorId_fkey" FOREIGN KEY ("contadorId") REFERENCES "CONTADOR"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
